### ISSUE TITLE
Pin Specific Requirement for lm_dataformat

### ISSUE THREAD

**Issue by trisongz** [EleutherAI/GPTNeo#71]
For some reason, multithreading isn't playing nice with the latest version of lm_dataformat and throws an error when using create_tfrecords.py

```
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "data/create_tfrecords.py", line 230, in create_file
    for d in data:
  File "data/create_tfrecords.py", line 221, in _archive_to_files
    for s in g:
  File "/usr/local/lib/python3.6/dist-packages/lm_dataformat/__init__.py", line 119, in stream_data
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "data/create_tfrecords.py", line 278, in <module>
    for i in tqdm(pool.imap(create_file, enumerate(file_chunks)), total=len(file_chunks)):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AssertionError: daemonic processes are not allowed to have children
  0% 0/104 [00:00<?, ?it/s]
```

The last version I was able to test and validate working is

pip install git+git://github.com/leogao2/lm_dataformat.git@f77f6e86d36306f0ecd4a8b47ee8223d5e491b4a

Great work so far - really excited to see GPTNeo progress!

**Comment by sdtblck** [comment]
As far as i know, lm_dataformat doesn't play well in general with multithreading - but please create an issue over there if possible.
